# This YAML file is intended as a template for adding a new country. All values are set to null.
# The first step is to rename the YAML file with the lowercase country ISO3 code, i.e. ${ISO3}.yml

# Settings for the country administrative boundaries
admin:
  # The name of the unzipped directory containing the shapefile (should have the same name as the shapefile)
  directory: ~
  # The ISO 639-1 of the primary language for the admin names, which in the COD files usually appears in the
  # column headers as e.g. ADMIN2_${ISO 639-1}
  language: ~
# Settings for the mobility matrix
mobility:
  scaling_factor:
    # Household size from
    # https://population.un.org/Household/index.html#/countries/
    # (see documentation if country is not available)
    household_size: ~
    # Motor vehicle fraction from
    # https://www.who.int/violence_injury_prevention/road_safety_status/country_profiles/en/
    # by taking the total population divided by the number of registered vehicles
    # (see documentation if country is not available)
    motor_vehicle_fraction: ~
# Settings for vulnerability
vulnerability:
  ghs:
    # Check GHS: https://ghsl.jrc.ec.europa.eu/download.php for the squares that cover the country in question.
    # Double check the coverage by displaying the admin file over the GHS rasters in QGIS.
    # Format should be a list of integer pairs (column, row)
    column_row_pairs:
      - (~, ~)
      - (~, ~)
  ipc:
    # Name of IPC file, leave '~' if IPC data is not available
    filename: Congo, DRC - IPC Analysis 2019-2020.xlsx
    # The last row containing data
    last_row: 147
    # The highest admin level in the file (should be 1 or 2)
    admin_level: 2
    # Admin names that need replacement to match the admin region shapefile.
    # You can get these by running the vulnerability script and it will warn of any admin names not found.
    # Should be of the format $ipc_name: $admin_region_name
    replace_dict:
      # Admin 2
      level_2_ipc_name : ~
      # Admin 1
      level_1_ipc_name : ~
      # Country name
      # It's also helpful to replace the country name as it appears in the IPC file with a blank string,
      # otherwise you will get warnings
      country_name:
  solid_fuels:
    # from https://www.who.int/nmh/countries/
    # expressed as fraction (e.g. 0.2) instead of percentage (e.g. 20) 
    frac_urban: ~
    frac_rural: ~
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    # expressed as fraction (e.g. 0.2) instead of percentage (e.g. 20) 
    # this is the sum of 'Limited' and 'No facility' in the 'Hygiene' tab of the Household World file
    frac_urban: ~
    frac_rural: ~
  # from https://www.who.int/nmh/countries/2018/
  # expressed as fraction (e.g. 0.2) instead of percentage (e.g. 20) 
  raised_blood_pressure: ~
  # from https://www.who.int/nmh/countries/2018/
  # expressed as fraction (e.g. 0.2) instead of percentage (e.g. 20) 
  diabetes: ~
  # from https://vizhub.healthdata.org/tobacco/
  # expressed as fraction (e.g. 0.2) instead of percentage (e.g. 20) 
  smoking: ~
# TODO: covid section
covid:
  # URL of the COVID file to be downloaded (from HDX or elsewhere)
  url: ~
  # local filename of the COVID file 
  filename: covid_data.csv
  # header of the COVID-19 (if set to 1 the second row - HLX tag - is used)
  header: 1
  # skip the first row if using HLX tag as header
  skiprows: 0
  # True is the dataset contains case data
  cases: ~
  # True is the dataset contains death data
  deaths: ~
  # True if the dataset represent invidual case data (i.e. each row correspond to a patient)
  individual_case_data: ~
  # True is the data represent cumulative cases and deaths (instead of new cases and deaths)
  cumulative: ~
  # admin level provided (can be 1 or 2)
  admin_level: ~
  # for Somalia we have data at the federal state level (which is not ADM1 or 2)
  federal_state_dict: ~
  # ADM1 name column in the exposure file (the shapefile in the country folder) 
  adm1_name_exp: ~
  # ADM2 name field in the exposure file (the shapefile in the country folder) 
  adm2_name_exp: ~
  # format of the date in the COVID dataset
  date_format: ~
  # replace column values to match the ADMIN names in the exposure
  # used to get the pcodes from the exposure file
  replace_dict:
    old_name: ~
  # dictionary to map HLX tags in the COVID dataset to standard HLX tags used in teh model
  hlx_dict:
    "#old_hxl_name": ~
# Contact matrix settings
contact_matrix:
  # The sheet name of the country to use for the contact matrices
  country: ~
  # Whether the country falls in the first or second set of files (1 or 2)
  file_number: ~
# NPI settings
NPIs:
  # The URL of the published Google sheet with NPIs
  url: ~
